# Generated by Django 4.0.3 on 2024-02-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_automobilevo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
